nginxproxy:
  image: jwilder/nginx-proxy
  restart: always
  ports:
    - "80:80"
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"

alatag:
  build: .
  restart: always
  expose:
    - "80"
#    - "443"
  environment:
    VIRTUAL_HOST: alatag.com www.alatag.com
    VIRTUAL_PORT: 80
